# placehoder file to call existing workflow
name: "Integration Tests Workflow"

on:
  workflow_dispatch:

jobs:
  disabled-on-master:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled on master
        run: |
          echo "::error::This workflow is a placeholder on master. Use the release branches"
          exit 1